<a href="https://colab.research.google.com/github/advait-t/IPL_Datasets/blob/main/BDT_Extracting_match_Scorecards.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2008: **59** <br>
Series id: 313494<br>
match_id: 335982

2009: **59**<br>
sid: 374163<br>
mid: 392181

2010: **60**<br>
sid: 418064<br>
mid: 419106

2011: 74<br>
sid:466304<br>
mid:501198

2012: 76<br>
sid:520932<br>
mid:548306

2013: 76<br>
sid:586733<br>
mid:597998

2014: 60<br>
sid:695871<br>
mid:729279

2015: 60<br>
sid:791129<br>
mid:829705

2016: 60<br>
sid:968923<br>
mid:980901

2017: 60<br>
sid:1078425<br>
mid:1082591

2018: 60<br>
sid:1131611<br>
mid:1136561

2019: 60<br>
sid:1165643<br>
mid:1175356

2020: 60<br>
sid:1210595<br>
mid:1216492

In [ ]:
import itertools

In [ ]:
sid=[313494,374163,418064,466304,520932,586733,695871,791129,968923,1078425,1131611,1165643,1210595] #each season id on ESPN Cricinfo
mid=[335982,392181,419106,501198,548306,597998,729279,829705,980901,1082591,1136561,1175356,1216492] #1st MatchID of each season
season = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np

def extract_batting_data(series_id, match_id,season_id):

    URL = 'https://www.espncricinfo.com/series/'+ str(series_id) + '/scorecard/' + str(match_id)
    page = requests.get(URL)
    try:
        bs = BeautifulSoup(page.content, 'lxml')
        table_body=bs.find_all('tbody')
        batsmen_df = pd.DataFrame(columns=["Name","Description","Runs", "Balls", "4s", "6s", "SR", "Team","Match_id","Season"])
        for i, table in enumerate(table_body[0:4:2]):
            rows = table.find_all('tr')
            for row in rows[::2]:
                cols=row.find_all('td')
                cols=[x.text.strip() for x in cols]
                if cols[0] == 'Extras':
                    continue
                if len(cols) > 7:
                    batsmen_df = batsmen_df.append(pd.Series(
                    [re.sub(r"\W+", ' ', cols[0].split("(c)")[0]).strip(), cols[1], 
                    cols[2], cols[3], cols[5], cols[6], cols[7],i+1,match_id,season_id], 
                    index=batsmen_df.columns ), ignore_index=True)
                else:
                    batsmen_df = batsmen_df.append(pd.Series(
                    [re.sub(r"\W+", ' ', cols[0].split("(c)")[0]).strip(), cols[1], 
                    0, 0, 0, 0, 0, i+1], index = batsmen_df.columns), ignore_index=True)
    except:
        pass       
    # for i in range(2):
    #     dnb_row = bs.find_all("tfoot")[i].find_all("div")
    #     for c in dnb_row:
    #         dnb_cols = c.find_all('span')
    #         dnb = [x.text.strip().split("(c)")[0] for x in dnb_cols]
    #         dnb = filter(lambda item: item, [re.sub(r"\W+", ' ', x).strip() for x in dnb])
    #         for dnb_batsman in dnb:
    #             batsmen_df = batsmen_df.append(pd.Series([dnb_batsman, "DNB", 0, 0, 0, 0, 0, i+1], index = batsmen_df.columns), ignore_index =True)

    return batsmen_df

In [ ]:
batting_data1=[]
for n,i in enumerate(season):
    if (sid[n]==313494 and sid[n]==374163):
        a = 59
    elif (sid[n]==466304):
        a = 74
    elif (sid[n]==520932 and sid[n]==586733):
        a = 76
    else:
        a = 60
    for j in range(mid[n],mid[n]+a):
        print(i,j)
        x=extract_batting_data(series_id = i, match_id = j,season_id=i)
        batting_data1.append(x)
        batting_data=pd.concat(batting_data1)

1 335982
1 335983
1 335984
1 335985
1 335986
1 335987
1 335988
1 335989
1 335990
1 335991
1 335992
1 335993
1 335994
1 335995
1 335996
1 335997
1 335998
1 335999
1 336000
1 336001
1 336002
1 336003
1 336004
1 336005
1 336006
1 336007
1 336008
1 336009
1 336010
1 336011
1 336012
1 336013
1 336014
1 336015
1 336016
1 336017
1 336018
1 336019
1 336020
1 336021
1 336022
1 336023
1 336024
1 336025
1 336026
1 336027
1 336028
1 336029
1 336030
1 336031
1 336032
1 336033
1 336034
1 336035
1 336036
1 336037
1 336038
1 336039
1 336040
1 336041
2 392181
2 392182
2 392183
2 392184
2 392185
2 392186
2 392187
2 392188
2 392189
2 392190
2 392191
2 392192
2 392193
2 392194
2 392195
2 392196
2 392197
2 392198
2 392199
2 392200
2 392201
2 392202
2 392203
2 392204
2 392205
2 392206
2 392207
2 392208
2 392209
2 392210
2 392211
2 392212
2 392213
2 392214
2 392215
2 392216
2 392217
2 392218
2 392219
2 392220
2 392221
2 392222
2 392223
2 392224
2 392225
2 392226
2 392227
2 392228
2 392229
2 392230
2 392231
2 392232
2 392233
2 392234
2 392235
2 392236
2 392237
2 392238
2 392239
2 392240
3 419106
3 419107
3 419108
3 419109
3 419110
3 419111
3 419112
3 419113
3 419114
3 419115
3 419116
3 419117
3 419118
3 419119
3 419120
3 419121
3 419122
3 419123
3 419124
3 419125
3 419126
3 419127
3 419128
3 419129
3 419130
3 419131
3 419132
3 419133
3 419134
3 419135
3 419136
3 419137
3 419138
3 419139
3 419140
3 419141
3 419142
3 419143
3 419144
3 419145
3 419146
3 419147
3 419148
3 419149
3 419150
3 419151
3 419152
3 419153
3 419154
3 419155
3 419156
3 419157
3 419158
3 419159
3 419160
3 419161
3 419162
3 419163
3 419164
3 419165
4 501198
4 501199
4 501200
4 501201
4 501202
4 501203
4 501204
4 501205
4 501206
4 501207
4 501208
4 501209
4 501210
4 501211
4 501212
4 501213
4 501214
4 501215
4 501216
4 501217
4 501218
4 501219
4 501220
4 501221
4 501222
4 501223
4 501224
4 501225
4 501226
4 501227
4 501228
4 501229
4 501230
4 501231
4 501232
4 501233
4 501234
4 501235
4 501236
4 501237
4 501238
4 501239
4 501240
4 501241
4 501242
4 501243
4 501244
4 501245
4 501246
4 501247
4 501248
4 501249
4 501250
4 501251
4 501252
4 501253
4 501254
4 501255
4 501256
4 501257
4 501258
4 501259
4 501260
4 501261
4 501262
4 501263
4 501264
4 501265
4 501266
4 501267
4 501268
4 501269
4 501270
4 501271
5 548306
5 548307
5 548308
5 548309
5 548310
5 548311
5 548312
5 548313
5 548314
5 548315
5 548316
5 548317
5 548318
5 548319
5 548320
5 548321
5 548322
5 548323
5 548324
5 548325
5 548326
5 548327
5 548328
5 548329
5 548330
5 548331
5 548332
5 548333
5 548334
5 548335
5 548336
5 548337
5 548338
5 548339
5 548340
5 548341
5 548342
5 548343
5 548344
5 548345
5 548346
5 548347
5 548348
5 548349
5 548350
5 548351
5 548352
5 548353
5 548354
5 548355
5 548356
5 548357
5 548358
5 548359
5 548360
5 548361
5 548362
5 548363
5 548364
5 548365
6 597998
6 597999
6 598000
6 598001
6 598002
6 598003
6 598004
6 598005
6 598006
6 598007
6 598008
6 598009
6 598010
6 598011
6 598012
6 598013
6 598014
6 598015
6 598016
6 598017
6 598018
6 598019
6 598020
6 598021
6 598022
6 598023
6 598024
6 598025
6 598026
6 598027
6 598028
6 598029
6 598030
6 598031
6 598032
6 598033
6 598034
6 598035
6 598036
6 598037
6 598038
6 598039
6 598040
6 598041
6 598042
6 598043
6 598044
6 598045
6 598046
6 598047
6 598048
6 598049
6 598050
6 598051
6 598052
6 598053
6 598054
6 598055
6 598056
6 598057
7 729279
7 729280
7 729281
7 729282
7 729283
7 729284
7 729285
7 729286
7 729287
7 729288
7 729289
7 729290
7 729291
7 729292
7 729293
7 729294
7 729295
7 729296
7 729297
7 729298
7 729299
7 729300
7 729301
7 729302
7 729303
7 729304
7 729305
7 729306
7 729307
7 729308
7 729309
7 729310
7 729311
7 729312
7 729313
7 729314
7 729315
7 729316
7 729317
7 729318
7 729319
7 729320
7 729321
7 729322
7 729323
7 729324
7 729325
7 729326
7 729327
7 729328
7 729329
7 729330
7 729331
7 729332
7 729333
7 729334
7 729335
7 729336
7 729337
7 729338
8 829705
8 829706
8 829707
8 829708
8 829709
8 829710
8 829711
8 829712
8 829713
8 829714
8 829715
8 829716
8 829717
8 829718
8 829719
8 829720
8 829721
8 829722
8 829723
8 829724
8 829725
8 829726
8 829727
8 829728
8 829729
8 829730
8 829731
8 829732
8 829733
8 829734
8 829735
8 829736
8 829737
8 829738
8 829739
8 829740
8 829741
8 829742
8 829743
8 829744
8 829745
8 829746
8 829747
8 829748
8 829749
8 829750
8 829751
8 829752
8 829753
8 829754
8 829755
8 829756
8 829757
8 829758
8 829759
8 829760
8 829761
8 829762
8 829763
8 829764
9 980901
9 980902
9 980903
9 980904
9 980905
9 980906
9 980907
9 980908
9 980909
9 980910
9 980911
9 980912
9 980913
9 980914
9 980915
9 980916
9 980917
9 980918
9 980919
9 980920
9 980921
9 980922
9 980923
9 980924
9 980925
9 980926
9 980927
9 980928
9 980929
9 980930
9 980931
9 980932
9 980933
9 980934
9 980935
9 980936
9 980937
9 980938
9 980939
9 980940
9 980941
9 980942
9 980943
9 980944
9 980945
9 980946
9 980947
9 980948
9 980949
9 980950
9 980951
9 980952
9 980953
9 980954
9 980955
9 980956
9 980957
9 980958
9 980959
9 980960
10 1082591
10 1082592
10 1082593
10 1082594
10 1082595
10 1082596
10 1082597
10 1082598
10 1082599
10 1082600
10 1082601
10 1082602
10 1082603
10 1082604
10 1082605
10 1082606
10 1082607
10 1082608
10 1082609
10 1082610
10 1082611
10 1082612
10 1082613
10 1082614
10 1082615
10 1082616
10 1082617
10 1082618
10 1082619
10 1082620
10 1082621
10 1082622
10 1082623
10 1082624
10 1082625
10 1082626
10 1082627
10 1082628
10 1082629
10 1082630
10 1082631
10 1082632
10 1082633
10 1082634
10 1082635
10 1082636
10 1082637
10 1082638
10 1082639
10 1082640
10 1082641
10 1082642
10 1082643
10 1082644
10 1082645
10 1082646
10 1082647
10 1082648
10 1082649
10 1082650
11 1136561
11 1136562
11 1136563
11 1136564
11 1136565
11 1136566
11 1136567
11 1136568
11 1136569
11 1136570
11 1136571
11 1136572
11 1136573
11 1136574
11 1136575
11 1136576
11 1136577
11 1136578
11 1136579
11 1136580
11 1136581
11 1136582
11 1136583
11 1136584
11 1136585
11 1136586
11 1136587
11 1136588
11 1136589
11 1136590
11 1136591
11 1136592
11 1136593
11 1136594
11 1136595
11 1136596
11 1136597
11 1136598
11 1136599
11 1136600
11 1136601
11 1136602
11 1136603
11 1136604
11 1136605
11 1136606
11 1136607
11 1136608
11 1136609
11 1136610
11 1136611
11 1136612
11 1136613
11 1136614
11 1136615
11 1136616
11 1136617
11 1136618
11 1136619
11 1136620
12 1175356
12 1175357
12 1175358
12 1175359
12 1175360
12 1175361
12 1175362
12 1175363
12 1175364
12 1175365
12 1175366
12 1175367
12 1175368
12 1175369
12 1175370
12 1175371
12 1175372
12 1175373
12 1175374
12 1175375
12 1175376
12 1175377
12 1175378
12 1175379
12 1175380
12 1175381
12 1175382
12 1175383
12 1175384
12 1175385
12 1175386
12 1175387
12 1175388
12 1175389
12 1175390
12 1175391
12 1175392
12 1175393
12 1175394
12 1175395
12 1175396
12 1175397
12 1175398
12 1175399
12 1175400
12 1175401
12 1175402
12 1175403
12 1175404
12 1175405
12 1175406
12 1175407
12 1175408
12 1175409
12 1175410
12 1175411
12 1175412
12 1175413
12 1175414
12 1175415
13 1216492
13 1216493
13 1216494
13 1216495
13 1216496
13 1216497
13 1216498
13 1216499
13 1216500
13 1216501
13 1216502
13 1216503
13 1216504
13 1216505
13 1216506
13 1216507
13 1216508
13 1216509
13 1216510
13 1216511
13 1216512
13 1216513
13 1216514
13 1216515
13 1216516
13 1216517
13 1216518
13 1216519
13 1216520
13 1216521
13 1216522
13 1216523
13 1216524
13 1216525
13 1216526
13 1216527
13 1216528
13 1216529
13 1216530
13 1216531
13 1216532
13 1216533
13 1216534
13 1216535
13 1216536
13 1216537
13 1216538
13 1216539
13 1216540
13 1216541
13 1216542
13 1216543
13 1216544
13 1216545
13 1216546
13 1216547
13 1216548
13 1216549
13 1216550
13 1216551

In [ ]:
batting_data.tail(20)

                Name                         Description  ... Match_id Season
5    Shimron Hetmyer                    b Mohammed Shami  ...  1216546     13
6           KL Rahul                      c Sams b Patel  ...  1216546     13
7     Mayank Agarwal              run out (Ashwin/†Pant)  ...  1216546     13
8        Chris Gayle                            b Ashwin  ...  1216546     13
9    Nicholas Pooran                    c †Pant b Rabada  ...  1216546     13
10     Glenn Maxwell                    c †Pant b Rabada  ...  1216546     13
11      Deepak Hooda                             not out  ...  1216546     13
12     James Neesham                             not out  ...  1216546     13
0   Devdutt Padikkal                   c Pollard b Boult  ...  1216547     13
1        Aaron Finch                   c Pollard b Boult  ...  1216547     13
2        Virat Kohli                   c Sharma b Chahar  ...  1216547     13
3     AB de Villiers                             not out  ...  1216547     13
4        Shivam Dube                             not out  ...  1216547     13
5       Rohit Sharma  c sub (P Negi) b Washington Sundar  ...  1216547     13
6    Quinton de Kock             c sub (P Negi) b Chahal  ...  1216547     13
7   Suryakumar Yadav              c †de Villiers b Udana  ...  1216547     13
8       Ishan Kishan                  c Padikkal b Udana  ...  1216547     13
9      Hardik Pandya              c sub (P Negi) b Zampa  ...  1216547     13
10    Kieron Pollard                             not out  ...  1216547     13
11     Krunal Pandya                             not out  ...  1216547     13

[20 rows x 10 columns]

In [ ]:
def extract_bowling_data(series_id, match_id,season_id):

    URL = 'https://www.espncricinfo.com/series/'+ str(series_id) + '/scorecard/' + str(match_id)
    page = requests.get(URL)
    try:
        bs = BeautifulSoup(page.content, 'lxml')

        table_body=bs.find_all('tbody')
        bowler_df = pd.DataFrame(columns=['Name', 'Overs', 'Maidens', 'Runs', 'Wickets',
                                        'Econ', 'Dots', '4s', '6s', 'Wd', 'Nb','Team','Match_id','Season'])
        for i, table in enumerate(table_body[1:4:2]):
            rows = table.find_all('tr')
            for row in rows:
                cols=row.find_all('td')
                cols=[x.text.strip() for x in cols]
                bowler_df = bowler_df.append(pd.Series([cols[0], cols[1], cols[2], cols[3], cols[4], cols[5], 
                                                        cols[6], cols[7], cols[8], cols[9], cols[10], (i==0)+1,match_id,season_id], 
                                                    index=bowler_df.columns ), ignore_index=True)
    except:
        pass
    return bowler_df

In [ ]:
bowling_data1=[]
for n,i in enumerate(season):
    if (sid[n]==313494 and sid[n]==374163):
        a = 59
    elif (sid[n]==466304):
        a = 74
    elif (sid[n]==520932 and sid[n]==586733):
        a = 76
    else:
        a = 60
    for j in range(mid[n],mid[n]+a):
        print(i,j)
        x=extract_bowling_data(series_id = i, match_id = j,season_id=i)
        bowling_data1.append(x)
        bowling_data=pd.concat(bowling_data1)

1 335982
1 335983
1 335984
1 335985
1 335986
1 335987
1 335988
1 335989
1 335990
1 335991
1 335992
1 335993
1 335994
1 335995
1 335996
1 335997
1 335998
1 335999
1 336000
1 336001
1 336002
1 336003
1 336004
1 336005
1 336006
1 336007
1 336008
1 336009
1 336010
1 336011
1 336012
1 336013
1 336014
1 336015
1 336016
1 336017
1 336018
1 336019
1 336020
1 336021
1 336022
1 336023
1 336024
1 336025
1 336026
1 336027
1 336028
1 336029
1 336030
1 336031
1 336032
1 336033
1 336034
1 336035
1 336036
1 336037
1 336038
1 336039
1 336040
1 336041
2 392181
2 392182
2 392183
2 392184
2 392185
2 392186
2 392187
2 392188
2 392189
2 392190
2 392191
2 392192
2 392193
2 392194
2 392195
2 392196
2 392197
2 392198
2 392199
2 392200
2 392201
2 392202
2 392203
2 392204
2 392205
2 392206
2 392207
2 392208
2 392209
2 392210
2 392211
2 392212
2 392213
2 392214
2 392215
2 392216
2 392217
2 392218
2 392219
2 392220
2 392221
2 392222
2 392223
2 392224
2 392225
2 392226
2 392227
2 392228
2 392229
2 392230
2 392231
2 392232
2 392233
2 392234
2 392235
2 392236
2 392237
2 392238
2 392239
2 392240
3 419106
3 419107
3 419108
3 419109
3 419110
3 419111
3 419112
3 419113
3 419114
3 419115
3 419116
3 419117
3 419118
3 419119
3 419120
3 419121
3 419122
3 419123
3 419124
3 419125
3 419126
3 419127
3 419128
3 419129
3 419130
3 419131
3 419132
3 419133
3 419134
3 419135
3 419136
3 419137
3 419138
3 419139
3 419140
3 419141
3 419142
3 419143
3 419144
3 419145
3 419146
3 419147
3 419148
3 419149
3 419150
3 419151
3 419152
3 419153
3 419154
3 419155
3 419156
3 419157
3 419158
3 419159
3 419160
3 419161
3 419162
3 419163
3 419164
3 419165
4 501198
4 501199
4 501200
4 501201
4 501202
4 501203
4 501204
4 501205
4 501206
4 501207
4 501208
4 501209
4 501210
4 501211
4 501212
4 501213
4 501214
4 501215
4 501216
4 501217
4 501218
4 501219
4 501220
4 501221
4 501222
4 501223
4 501224
4 501225
4 501226
4 501227
4 501228
4 501229
4 501230
4 501231
4 501232
4 501233
4 501234
4 501235
4 501236
4 501237
4 501238
4 501239
4 501240
4 501241
4 501242
4 501243
4 501244
4 501245
4 501246
4 501247
4 501248
4 501249
4 501250
4 501251
4 501252
4 501253
4 501254
4 501255
4 501256
4 501257
4 501258
4 501259
4 501260
4 501261
4 501262
4 501263
4 501264
4 501265
4 501266
4 501267
4 501268
4 501269
4 501270
4 501271
5 548306
5 548307
5 548308
5 548309
5 548310
5 548311
5 548312
5 548313
5 548314
5 548315
5 548316
5 548317
5 548318
5 548319
5 548320
5 548321
5 548322
5 548323
5 548324
5 548325
5 548326
5 548327
5 548328
5 548329
5 548330
5 548331
5 548332
5 548333
5 548334
5 548335
5 548336
5 548337
5 548338
5 548339
5 548340
5 548341
5 548342
5 548343
5 548344
5 548345
5 548346
5 548347
5 548348
5 548349
5 548350
5 548351
5 548352
5 548353
5 548354
5 548355
5 548356
5 548357
5 548358
5 548359
5 548360
5 548361
5 548362
5 548363
5 548364
5 548365
6 597998
6 597999
6 598000
6 598001
6 598002
6 598003
6 598004
6 598005
6 598006
6 598007
6 598008
6 598009
6 598010
6 598011
6 598012
6 598013
6 598014
6 598015
6 598016
6 598017
6 598018
6 598019
6 598020
6 598021
6 598022
6 598023
6 598024
6 598025
6 598026
6 598027
6 598028
6 598029
6 598030
6 598031
6 598032
6 598033
6 598034
6 598035
6 598036
6 598037
6 598038
6 598039
6 598040
6 598041
6 598042
6 598043
6 598044
6 598045
6 598046
6 598047
6 598048
6 598049
6 598050
6 598051
6 598052
6 598053
6 598054
6 598055
6 598056
6 598057
7 729279
7 729280
7 729281
7 729282
7 729283
7 729284
7 729285
7 729286
7 729287
7 729288
7 729289
7 729290
7 729291
7 729292
7 729293
7 729294
7 729295
7 729296
7 729297
7 729298
7 729299
7 729300
7 729301
7 729302
7 729303
7 729304
7 729305
7 729306
7 729307
7 729308
7 729309
7 729310
7 729311
7 729312
7 729313
7 729314
7 729315
7 729316
7 729317
7 729318
7 729319
7 729320
7 729321
7 729322
7 729323
7 729324
7 729325
7 729326
7 729327
7 729328
7 729329
7 729330
7 729331
7 729332
7 729333
7 729334
7 729335
7 729336
7 729337
7 729338
8 829705
8 829706
8 829707
8 829708
8 829709
8 829710
8 829711
8 829712
8 829713
8 829714
8 829715
8 829716
8 829717
8 829718
8 829719
8 829720
8 829721
8 829722
8 829723
8 829724
8 829725
8 829726
8 829727
8 829728
8 829729
8 829730
8 829731
8 829732
8 829733
8 829734
8 829735
8 829736
8 829737
8 829738
8 829739
8 829740
8 829741
8 829742
8 829743
8 829744
8 829745
8 829746
8 829747
8 829748
8 829749
8 829750
8 829751
8 829752
8 829753
8 829754
8 829755
8 829756
8 829757
8 829758
8 829759
8 829760
8 829761
8 829762
8 829763
8 829764
9 980901
9 980902
9 980903
9 980904
9 980905
9 980906
9 980907
9 980908
9 980909
9 980910
9 980911
9 980912
9 980913
9 980914
9 980915
9 980916
9 980917
9 980918
9 980919
9 980920
9 980921
9 980922
9 980923
9 980924
9 980925
9 980926
9 980927
9 980928
9 980929
9 980930
9 980931
9 980932
9 980933
9 980934
9 980935
9 980936
9 980937
9 980938
9 980939
9 980940
9 980941
9 980942
9 980943
9 980944
9 980945
9 980946
9 980947
9 980948
9 980949
9 980950
9 980951
9 980952
9 980953
9 980954
9 980955
9 980956
9 980957
9 980958
9 980959
9 980960
10 1082591
10 1082592
10 1082593
10 1082594
10 1082595
10 1082596
10 1082597
10 1082598
10 1082599
10 1082600
10 1082601
10 1082602
10 1082603
10 1082604
10 1082605
10 1082606
10 1082607
10 1082608
10 1082609
10 1082610
10 1082611
10 1082612
10 1082613
10 1082614
10 1082615
10 1082616
10 1082617
10 1082618
10 1082619
10 1082620
10 1082621
10 1082622
10 1082623
10 1082624
10 1082625
10 1082626
10 1082627
10 1082628
10 1082629
10 1082630
10 1082631
10 1082632
10 1082633
10 1082634
10 1082635
10 1082636
10 1082637
10 1082638
10 1082639
10 1082640
10 1082641
10 1082642
10 1082643
10 1082644
10 1082645
10 1082646
10 1082647
10 1082648
10 1082649
10 1082650
11 1136561
11 1136562
11 1136563
11 1136564
11 1136565
11 1136566
11 1136567
11 1136568
11 1136569
11 1136570
11 1136571
11 1136572
11 1136573
11 1136574
11 1136575
11 1136576
11 1136577
11 1136578
11 1136579
11 1136580
11 1136581
11 1136582
11 1136583
11 1136584
11 1136585
11 1136586
11 1136587
11 1136588
11 1136589
11 1136590
11 1136591
11 1136592
11 1136593
11 1136594
11 1136595
11 1136596
11 1136597
11 1136598
11 1136599
11 1136600
11 1136601
11 1136602
11 1136603
11 1136604
11 1136605
11 1136606
11 1136607
11 1136608
11 1136609
11 1136610
11 1136611
11 1136612
11 1136613
11 1136614
11 1136615
11 1136616
11 1136617
11 1136618
11 1136619
11 1136620
12 1175356
12 1175357
12 1175358
12 1175359
12 1175360
12 1175361
12 1175362
12 1175363
12 1175364
12 1175365
12 1175366
12 1175367
12 1175368
12 1175369
12 1175370
12 1175371
12 1175372
12 1175373
12 1175374
12 1175375
12 1175376
12 1175377
12 1175378
12 1175379
12 1175380
12 1175381
12 1175382
12 1175383
12 1175384
12 1175385
12 1175386
12 1175387
12 1175388
12 1175389
12 1175390
12 1175391
12 1175392
12 1175393
12 1175394
12 1175395
12 1175396
12 1175397
12 1175398
12 1175399
12 1175400
12 1175401
12 1175402
12 1175403
12 1175404
12 1175405
12 1175406
12 1175407
12 1175408
12 1175409
12 1175410
12 1175411
12 1175412
12 1175413
12 1175414
12 1175415
13 1216492
13 1216493
13 1216494
13 1216495
13 1216496
13 1216497
13 1216498
13 1216499
13 1216500
13 1216501
13 1216502
13 1216503
13 1216504
13 1216505
13 1216506
13 1216507
13 1216508
13 1216509
13 1216510
13 1216511
13 1216512
13 1216513
13 1216514
13 1216515
13 1216516
13 1216517
13 1216518
13 1216519
13 1216520
13 1216521
13 1216522
13 1216523
13 1216524
13 1216525
13 1216526
13 1216527
13 1216528
13 1216529
13 1216530
13 1216531
13 1216532
13 1216533
13 1216534
13 1216535
13 1216536
13 1216537
13 1216538
13 1216539
13 1216540
13 1216541
13 1216542
13 1216543
13 1216544
13 1216545
13 1216546
13 1216547
13 1216548
13 1216549
13 1216550
13 1216551

In [ ]:
bowling_data = bpwling_data

In [ ]:
bowling_data.head()

             Name Overs Maidens Runs Wickets  ... Wd Nb Team Match_id Season
0   Praveen Kumar     4       0   38       0  ...  1  0    2   335982      1
1     Zaheer Khan     4       0   38       1  ...  0  0    2   335982      1
2   Ashley Noffke     4       0   40       1  ...  1  0    2   335982      1
3  Jacques Kallis     4       0   48       1  ...  1  0    2   335982      1
4     Sunil Joshi     3       0   26       0  ...  0  0    2   335982      1

[5 rows x 14 columns]

In [ ]:
batting_data.to_csv('/content/drive/MyDrive/batting_data_IPL.csv')

In [ ]:
bowling_data.to_csv('/content/drive/MyDrive/bowling_data_IPL.csv')

In [ ]:
batting_data.shape

(9727, 10)

In [ ]:
bowling_data.shape

(7579, 14)

In [ ]:
batting_data.isnull().sum(axis = 0)

Name           0
Description    0
Runs           0
Balls          0
4s             0
6s             0
SR             0
Team           0
Match_id       0
Season         0
dtype: int64

In [ ]:
bowling_data.isnull().sum(axis = 0)

Name        0
Overs       0
Maidens     0
Runs        0
Wickets     0
Econ        0
Dots        0
4s          0
6s          0
Wd          0
Nb          0
Team        0
Match_id    0
Season      0
dtype: int64